name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        cd SocialNetworking
        swift build -v
    - name: Run tests
      run: |
        cd SocialNetworking
        swift test -v
